import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useState } from 'react';
import { api } from "~/utils/api";
import { v2 as cloudinary } from "cloudinary";

export default function Home(props) {
  const user = useUser();

  const { data } = api.recetas.getRecipes.useQuery();

  return (
    <>
      <Head>
        <title>Cociname</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">Cocina</span> .me
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <div className="flex flex-col">
                {data?.map((receta) => (
                  <div key={(receta.id)}>{receta.titulo}</div>
                ))}
              </div>
          </div>
        </div>
      </main>
    </>
  );
}
